/*
 * clawt-cloud-init.c - A NoCloud seed, so a stock cloud image is reachable
 *
 * Copyright (C) 2026
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of clawtilla.
 */

#include "clawtilla.h"
#include "computer/clawt-cloud-init.h"

/*
 * The label NoCloud looks for.  cloud-init finds the seed by filesystem
 * label and nothing else, so this is not a name we are free to choose.
 */
#define SEED_VOLUME_ID "cidata"

/*
 * Emits a YAML double-quoted scalar.
 *
 * A public key's comment is whatever was on the machine that made it, and
 * a hostname comes from an agent id, so neither is guaranteed to be a
 * plain scalar.  Quoting everything is cheaper than deciding each time.
 */
static void
append_quoted(GString *out, const gchar *value)
{
    const gchar *p;

    g_string_append_c(out, '"');

    for (p = value; *p != '\0'; p++) {
        if (*p == '\\' || *p == '"')
            g_string_append_c(out, '\\');
        g_string_append_c(out, *p);
    }

    g_string_append_c(out, '"');
}

gchar *
clawt_cloud_init_build_user_data(const gchar *user,
                                 const gchar *authorized_key,
                                 const gchar *hostname)
{
    g_autoptr(GString) out = NULL;
    gboolean is_root;

    g_return_val_if_fail(user != NULL, NULL);

    out = g_string_new(NULL);
    is_root = g_strcmp0(user, "root") == 0;

    g_string_append(out,
        "#cloud-config\n"
        "# Generated by clawtilla, and rebuilt whenever the login, the key\n"
        "# or the hostname changes.  Edit computer.vm.* in clawtilla.yaml\n"
        "# rather than this file.\n");

    if (hostname != NULL) {
        g_string_append(out, "hostname: ");
        append_quoted(out, hostname);
        g_string_append(out, "\npreserve_hostname: false\n");
    }

    /*
     * No password is ever set on the account, so leaving password
     * authentication enabled could only ever admit somebody else.
     */
    g_string_append(out, "ssh_pwauth: false\n");

    /*
     * Left at its default, cloud-init prefixes root's authorized_keys with
     * a command that replaces the login with a message telling you not to
     * log in as root -- so the key appears installed and the login still
     * fails.
     */
    g_string_append_printf(out, "disable_root: %s\n",
                           is_root ? "false" : "true");

    /*
     * The key is named twice, and it has to be.
     *
     * cloud-init installs a key listed inside a `users:` entry while
     * *creating* that account, and it skips an account that already
     * exists -- which root always does.  So for the default login the
     * users list silently authorises nothing, and the guest boots with a
     * key it has never heard of.  The top-level list is handled by a
     * different module, which writes root's authorized_keys directly.
     *
     * Neither one covers both cases, so both are written.  A key
     * installed twice is the same key.
     */
    if (authorized_key != NULL) {
        g_string_append(out, "ssh_authorized_keys:\n  - ");
        append_quoted(out, authorized_key);
        g_string_append_c(out, '\n');
    }

    /*
     * Naming a user without "default" in the list means the image's own
     * default login -- fedora, debian, ubuntu, and so on -- is never
     * created, so the guest has exactly the one account clawtilla knows
     * about.
     */
    g_string_append(out, "users:\n  - name: ");
    append_quoted(out, user);
    g_string_append(out, "\n    lock_passwd: true\n");

    /*
     * No shell is named on purpose.  Asking for one the image does not
     * have leaves an account that exists and cannot log in, and cloud-init
     * already knows the distribution's default.
     */
    if (!is_root)
        g_string_append(out, "    sudo: \"ALL=(ALL) NOPASSWD:ALL\"\n");

    if (authorized_key != NULL) {
        g_string_append(out, "    ssh_authorized_keys:\n      - ");
        append_quoted(out, authorized_key);
        g_string_append_c(out, '\n');
    }

    return g_string_free(g_steal_pointer(&out), FALSE);
}

gchar *
clawt_cloud_init_build_meta_data(const gchar *instance_id,
                                 const gchar *hostname)
{
    g_autoptr(GString) out = NULL;

    g_return_val_if_fail(instance_id != NULL, NULL);

    out = g_string_new(NULL);

    g_string_append(out, "instance-id: ");
    append_quoted(out, instance_id);
    g_string_append_c(out, '\n');

    if (hostname != NULL) {
        g_string_append(out, "local-hostname: ");
        append_quoted(out, hostname);
        g_string_append_c(out, '\n');
    }

    return g_string_free(g_steal_pointer(&out), FALSE);
}

const gchar *
clawt_cloud_init_find_tool(void)
{
    static const gchar *candidates[] = {
        "xorrisofs", "genisoimage", "mkisofs", NULL
    };
    gsize i;

    for (i = 0; candidates[i] != NULL; i++) {
        g_autofree gchar *found = g_find_program_in_path(candidates[i]);

        if (found != NULL)
            return candidates[i];
    }

    return NULL;
}

GStrv
clawt_cloud_init_build_iso_argv(const gchar *tool,
                                const gchar *iso_path,
                                const gchar *source_dir)
{
    GPtrArray *argv;

    g_return_val_if_fail(tool != NULL, NULL);
    g_return_val_if_fail(iso_path != NULL, NULL);
    g_return_val_if_fail(source_dir != NULL, NULL);

    argv = g_ptr_array_new_with_free_func(g_free);

    /*
     * Short options only.  xorrisofs, genisoimage and mkisofs agree on
     * these; they do not all agree on the long spellings.
     */
    g_ptr_array_add(argv, g_strdup(tool));
    g_ptr_array_add(argv, g_strdup("-o"));
    g_ptr_array_add(argv, g_strdup(iso_path));
    g_ptr_array_add(argv, g_strdup("-V"));
    g_ptr_array_add(argv, g_strdup(SEED_VOLUME_ID));
    g_ptr_array_add(argv, g_strdup("-J"));
    g_ptr_array_add(argv, g_strdup("-r"));
    g_ptr_array_add(argv, g_strdup(source_dir));
    g_ptr_array_add(argv, NULL);

    return (GStrv)g_ptr_array_free(argv, FALSE);
}

gchar *
clawt_cloud_init_write_seed(const gchar  *dir,
                            const gchar  *instance_id,
                            const gchar  *user,
                            const gchar  *authorized_key,
                            const gchar  *hostname,
                            GError      **error)
{
    g_autofree gchar *seed_dir = NULL;
    g_autofree gchar *user_data = NULL;
    g_autofree gchar *meta_data = NULL;
    g_autofree gchar *user_data_path = NULL;
    g_autofree gchar *meta_data_path = NULL;
    g_autofree gchar *iso_path = NULL;
    g_autofree gchar *existing = NULL;
    g_auto(GStrv) argv = NULL;
    g_autoptr(GSubprocess) process = NULL;
    const gchar *tool;

    g_return_val_if_fail(dir != NULL, NULL);
    g_return_val_if_fail(instance_id != NULL, NULL);
    g_return_val_if_fail(user != NULL, NULL);

    seed_dir = g_build_filename(dir, "cloud-init", NULL);

    if (!clawt_ensure_dir(seed_dir, 0700, error))
        return NULL;

    user_data = clawt_cloud_init_build_user_data(user, authorized_key,
                                                 hostname);
    meta_data = clawt_cloud_init_build_meta_data(instance_id, hostname);

    user_data_path = g_build_filename(seed_dir, "user-data", NULL);
    meta_data_path = g_build_filename(seed_dir, "meta-data", NULL);
    iso_path = g_build_filename(dir, "seed.iso", NULL);

    /*
     * Rebuilding an identical seed on every start would be wasted work,
     * and would keep handing the guest a new image to notice.
     */
    if (g_file_get_contents(user_data_path, &existing, NULL, NULL) &&
        g_strcmp0(existing, user_data) == 0 &&
        g_file_test(iso_path, G_FILE_TEST_EXISTS))
        return g_steal_pointer(&iso_path);

    if (!clawt_write_file_atomic(user_data_path, user_data, -1, 0600, FALSE,
                                 error))
        return NULL;

    if (!clawt_write_file_atomic(meta_data_path, meta_data, -1, 0600, FALSE,
                                 error))
        return NULL;

    tool = clawt_cloud_init_find_tool();

    if (tool == NULL) {
        g_set_error_literal(error, CLAWT_ERROR,
                            CLAWT_ERROR_COMPUTER_PROVISION,
                            "no ISO writer is installed, so this VM cannot "
                            "be handed its cloud-init seed: install xorriso "
                            "(Fedora: xorriso), or set "
                            "computer.vm.cloud_init to false and put a "
                            "login and key into the image yourself");
        return NULL;
    }

    argv = clawt_cloud_init_build_iso_argv(tool, iso_path, seed_dir);

    process = g_subprocess_newv((const gchar * const *)argv,
                                G_SUBPROCESS_FLAGS_STDOUT_SILENCE |
                                G_SUBPROCESS_FLAGS_STDERR_PIPE,
                                error);

    if (process == NULL) {
        g_prefix_error(error, "building the cloud-init seed: ");
        return NULL;
    }

    if (!g_subprocess_wait_check(process, NULL, error)) {
        g_prefix_error(error, "%s could not build %s: ", tool, iso_path);
        return NULL;
    }

    return g_steal_pointer(&iso_path);
}

gchar *
clawt_cloud_init_public_key(const gchar  *private_key_path,
                            GError      **error)
{
    g_autofree gchar *pub_path = NULL;
    g_autofree gchar *contents = NULL;
    g_autofree gchar *stdout_text = NULL;
    g_autofree gchar *stderr_text = NULL;
    g_autoptr(GSubprocess) process = NULL;

    g_return_val_if_fail(private_key_path != NULL, NULL);

    pub_path = g_strconcat(private_key_path, ".pub", NULL);

    if (g_file_get_contents(pub_path, &contents, NULL, NULL))
        return g_strstrip(g_steal_pointer(&contents));

    /*
     * A key generated elsewhere may have arrived without its .pub, which
     * is not a reason to refuse: the public half is derivable.
     */
    process = g_subprocess_new(G_SUBPROCESS_FLAGS_STDOUT_PIPE |
                               G_SUBPROCESS_FLAGS_STDERR_PIPE,
                               error,
                               "ssh-keygen", "-y", "-f", private_key_path,
                               NULL);

    if (process == NULL)
        return NULL;

    if (!g_subprocess_communicate_utf8(process, NULL, NULL, &stdout_text,
                                       &stderr_text, error))
        return NULL;

    if (g_subprocess_get_exit_status(process) != 0) {
        g_set_error(error, CLAWT_ERROR, CLAWT_ERROR_COMPUTER_PROVISION,
                    "could not read a public key from %s: %s -- note that "
                    "an encrypted key cannot be used here, because nothing "
                    "is present to type its passphrase",
                    private_key_path,
                    stderr_text != NULL ? g_strstrip(stderr_text)
                                        : "ssh-keygen failed");
        return NULL;
    }

    return g_strstrip(g_steal_pointer(&stdout_text));
}

gboolean
clawt_cloud_init_ensure_key(const gchar  *dir,
                            const gchar  *comment,
                            gchar       **key_path,
                            gchar       **public_key,
                            GError      **error)
{
    g_autofree gchar *path = NULL;
    g_autofree gchar *public = NULL;

    g_return_val_if_fail(dir != NULL, FALSE);
    g_return_val_if_fail(key_path != NULL, FALSE);
    g_return_val_if_fail(public_key != NULL, FALSE);

    if (!clawt_ensure_dir(dir, 0700, error))
        return FALSE;

    path = g_build_filename(dir, "id_ed25519", NULL);

    if (!g_file_test(path, G_FILE_TEST_EXISTS)) {
        g_autoptr(GSubprocess) process = NULL;

        process = g_subprocess_new(G_SUBPROCESS_FLAGS_STDOUT_SILENCE |
                                   G_SUBPROCESS_FLAGS_STDERR_PIPE,
                                   error,
                                   "ssh-keygen", "-t", "ed25519",
                                   "-N", "",
                                   "-C", comment != NULL ? comment
                                                         : "clawtilla",
                                   "-f", path, NULL);

        if (process == NULL) {
            g_prefix_error(error, "generating the VM's SSH key: ");
            return FALSE;
        }

        if (!g_subprocess_wait_check(process, NULL, error)) {
            g_prefix_error(error, "ssh-keygen could not create %s: ", path);
            return FALSE;
        }
    }

    public = clawt_cloud_init_public_key(path, error);

    if (public == NULL)
        return FALSE;

    *key_path = g_steal_pointer(&path);
    *public_key = g_steal_pointer(&public);

    return TRUE;
}
